//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApiMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiMsg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shop.Language.ApiMsg", typeof(ApiMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EXE {
            get {
                return ResourceManager.GetString("EXE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível criar a categoria.
        /// </summary>
        public static string EXE0001 {
            get {
                return ResourceManager.GetString("EXE0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não possivel atualizar a categoria.
        /// </summary>
        public static string EXE0002 {
            get {
                return ResourceManager.GetString("EXE0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essa categoria já foi atualizada.
        /// </summary>
        public static string EXE0003 {
            get {
                return ResourceManager.GetString("EXE0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possivel remover a categoria.
        /// </summary>
        public static string EXE0004 {
            get {
                return ResourceManager.GetString("EXE0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As categorias não foram encontradas, tente novamente mais tarde.
        /// </summary>
        public static string EXE0005 {
            get {
                return ResourceManager.GetString("EXE0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível listar os produtos.
        /// </summary>
        public static string EXE0006 {
            get {
                return ResourceManager.GetString("EXE0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível listar o produto.
        /// </summary>
        public static string EXE0007 {
            get {
                return ResourceManager.GetString("EXE0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível listar os produtos dessa categoria.
        /// </summary>
        public static string EXE0008 {
            get {
                return ResourceManager.GetString("EXE0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível salvar o produto.
        /// </summary>
        public static string EXE0009 {
            get {
                return ResourceManager.GetString("EXE0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse produto já foi atualizado.
        /// </summary>
        public static string EXE0010 {
            get {
                return ResourceManager.GetString("EXE0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não possível realizar a alteração do produto.
        /// </summary>
        public static string EXE0011 {
            get {
                return ResourceManager.GetString("EXE0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível remover o produto.
        /// </summary>
        public static string EXE0012 {
            get {
                return ResourceManager.GetString("EXE0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é obrigatorio.
        /// </summary>
        public static string ISE0001 {
            get {
                return ResourceManager.GetString("ISE0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ter no maximo {1} caracteres.
        /// </summary>
        public static string ISE0002 {
            get {
                return ResourceManager.GetString("ISE0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser do tipo {1}.
        /// </summary>
        public static string ISE0003 {
            get {
                return ResourceManager.GetString("ISE0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ter no minimo {1} caracteres.
        /// </summary>
        public static string ISE0004 {
            get {
                return ResourceManager.GetString("ISE0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve está entre os valores {1} e {2}.
        /// </summary>
        public static string ISE0005 {
            get {
                return ResourceManager.GetString("ISE0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria não encontrada.
        /// </summary>
        public static string ISE0006 {
            get {
                return ResourceManager.GetString("ISE0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria atualizada com sucesso.
        /// </summary>
        public static string ISE0007 {
            get {
                return ResourceManager.GetString("ISE0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria removida com sucesso.
        /// </summary>
        public static string ISE0008 {
            get {
                return ResourceManager.GetString("ISE0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse produto não existe.
        /// </summary>
        public static string ISE0009 {
            get {
                return ResourceManager.GetString("ISE0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe produtos dessa categoria.
        /// </summary>
        public static string ISE0010 {
            get {
                return ResourceManager.GetString("ISE0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto salvo com sucesso.
        /// </summary>
        public static string ISE0011 {
            get {
                return ResourceManager.GetString("ISE0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto alterado com sucesso.
        /// </summary>
        public static string ISE0012 {
            get {
                return ResourceManager.GetString("ISE0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto removido com sucesso..
        /// </summary>
        public static string ISE0013 {
            get {
                return ResourceManager.GetString("ISE0013", resourceCulture);
            }
        }
    }
}
